spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpastudy;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
 #       show_sql: true    생성하는 sql을 System.out으로 남김
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #hibernate가 생성하는 sql이 다 log로 남음